# Generated by Django 4.1.1 on 2023-01-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_question_id_alter_question_qname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=None),
        ),
    ]
