# Generated by Django 4.1.1 on 2023-01-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_result_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registernumber',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
